export const Strings = {
  app: {
    title: 'Maaltijden',
    addMealTitle: 'Maaltijd toevoegen',
    mealDetailTitle: 'Maaltijd Details',
  },
  tabs: {
    home: 'Home',
    statistics: 'Statistieken',
    add: 'Toevoegen',
    profile: 'Profiel',
  },
  home: {
    emptyState: 'Nog geen maaltijden toegevoegd.\nTik op + om te beginnen!',
    caloriesUnit: 'kcal',
    ingredientsLabel: 'ingrediënten',
  },
  addMeal: {
    mealNameLabel: 'Naam van de maaltijd',
    mealNamePlaceholder: 'bv. Ontbijt, Lunch, Avondeten',
    photoLabel: 'Foto van de maaltijd',
    photoButtonText: 'Foto maken',
    ingredientsLabel: 'Ingrediënten toevoegen',
    ingredientNamePlaceholder: 'Ingrediënt naam',
    caloriesPlaceholder: 'Calorieën',
    addButtonText: 'Toevoegen',
    totalCaloriesLabel: 'Totaal aantal calorieën',
    saveButtonText: 'Maaltijd opslaan',
  },
  validation: {
    emptyMealName: 'Voer een maaltijd naam in',
    emptyIngredientName: 'Voer een ingrediënt naam in',
    invalidCalories: 'Voer een geldig calorieën aantal in',
    noIngredients: 'Voeg minstens één ingrediënt toe',
    successTitle: 'Succes',
    successMessage: 'Maaltijd opgeslagen!',
    errorTitle: 'Fout',
  },
  common: {
    ok: 'OK',
  },
  statistics: {
    title: 'Statistieken',
    totalMeals: 'Totaal maaltijden',
    totalCalories: 'Totaal calorieën',
    averageCalories: 'Gemiddeld per maaltijd',
    mostUsedIngredients: 'Meest gebruikte ingrediënten',
    recentMeals: 'Recente maaltijden',
    noData: 'Nog geen statistieken beschikbaar.\nVoeg maaltijden toe om data te zien.',
    thisWeek: 'Deze week',
    thisMonth: 'Deze maand',
    allTime: 'Totaal',
  },
  profile: {
    title: 'Profiel',
    appInfo: 'App Informatie',
    appName: 'Calorie Tracker',
    version: 'Versie 1.0.0',
    description: 'Track je dagelijkse calorie-inname door maaltijden en ingrediënten toe te voegen.',
    features: 'Functies',
    feature1: '📊 Realtime statistieken',
    feature2: '🍽️ Maaltijden beheren',
    feature3: '🥗 Ingrediënten tracking',
    feature4: '📈 Calorie overzicht',
    settings: 'Instellingen',
    clearData: 'Wis alle data',
    clearDataConfirm: 'Weet je zeker dat je alle maaltijden wilt verwijderen?',
    cancel: 'Annuleren',
    delete: 'Verwijderen',
    dataCleared: 'Alle data is verwijderd',
  },
  mealDetail: {
    ingredients: 'Ingrediënten',
    totalCalories: 'Totaal',
    createdAt: 'Toegevoegd op',
    noPhoto: 'Geen foto beschikbaar',
    delete: 'Maaltijd verwijderen',
    deleteConfirm: 'Weet je zeker dat je deze maaltijd wilt verwijderen?',
  },
}
